[project]
name = "f5docs"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "lxml>=5.4.0",
    "pyyaml>=6.0.2",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
